### ISSUE TITLE
Upcoming events page

### ISSUE THREAD

**Issue by SaranjeetKaur** [rse-asia/RSE_Asia#12]
Add upcoming events page on the website

**Comment by georgioupanayiotis** [comment]
@SaranjeetKaur  can you please assign this to me?

**Comment by georgioupanayiotis** [comment]
@SaranjeetKaur can you assign myself ?

**Comment by SaranjeetKaur** [comment]
Hi @georgioupanayiotis, I've started work on this as it is a pre-planned task. However, you can join one of our Contributing Hours on any weekday of the month of October 2022 and collaborate with us: https://us06web.zoom.us/meeting/register/tZUocO2upjssG9Y2CTZbO717Q4Om8XZDTmJh
(Registration is required for joining the Contributing Hours and if you do so, please don't forget to save it on your calendar). Thank you for your interest!

**Comment by SaranjeetKaur** [comment]
As PR #30 is merged - this issue will be closed now!
